### ISSUE TITLE
Не могу подключить к webpack

### ISSUE THREAD

**Issue by dimensi** [chayka/jQuery.Scroolly#10]
Плагин никакую не подключается через webpack. 
ни через define, ни через require();

**Comment by coaperator** [comment]
испортирую библиотеку так:
`import 'sticky-kit/dist/sticky-kit.js';`

та же проблема, подскажите как завести?

**Comment by dimensi** [comment]
Офигеть, 2016. Парень, если ты сильно хочешь заюзать либу. Советую просто скопировать эти строчки https://github.com/chayka/jQuery.Scroolly/blob/master/src/jquery.scroolly.js#L19-L1262 и вставить в какой-нить у себя файлик, а потом импортнуть в него же jquery. 
Есть кстать тулза https://lebab.unibtc.me/editor которая может любой es3 код трансформировать в es5.

Сделаю форк и починю данную траблу.

**Comment by dimensi** [comment]
https://github.com/dimensi/jQuery.Scroolly, попробуй. Установи пакет прям через гит и просто импортни.
```js
import 'package';
```
