### ISSUE TITLE
dynamic container

### ISSUE THREAD

**Issue by denis76** [chayka/jQuery.Scroolly#6]
Hello!
What if we increased container height dynamically(by ajax call appended some items) and at that moment $(window).scrollTop() > 0 and scroolly is already initialized.

What are the correct steps to reinitialize scroolly to encounter new container height or whatever should be done to render properly when scrolling after appending?

**Comment by chayka** [comment]
Try to call scrolly.onResize(), if it won't work, try scrolly.onScroll(). If the problem remains ping me via skype: boris.mossounov and I'll try to help you.
Yeah that may be a nice update to watch sizes of elements and containers :)

**Comment by denis76** [comment]
Thank you very much indeed! 
$.scrolly.onResize() did the job.

**Comment by kosmom** [comment]
Add this method into wiki please as dinamical size change of containers
Добавьте метод в вики пожалуйста, как средство для решения проблем с динамическим содержимым
